services:
  fast-detect-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast-detect-gpt:latest
    container_name: fast-detect-gpt
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /workspace
    ports:
      - "7860:7860"
    volumes:
      - ./Fast-detect-gpt:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
    command: /bin/bash
