services:
  fast-detect-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    image: fast-detect-gpt:latest
    container_name: fast-detect-gpt
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./datasets:/app/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
    command: /bin/bash
